#!/usr/bin/env python3
# Only tested with Python3

import os, sys, getopt

from uni_shape import make_fonts, analyse

def usage():
	print('analyze_font [-f <infont>]')
	print('<infont>: .ttf file')
	sys.exit(2)

def main(argv):
	try:
		opts, args = getopt.getopt(argv, 'hf:', [])
	except getopt.GetoptError:
		usage()
	d = os.path.dirname(os.path.realpath(sys.argv[0]))
	f = d + '/fonts/NewGardinerSMP'
	for opt, arg in opts:
		if opt == '-h':
			usage()
		elif opt == '-f':
			f = d + '/fonts/' + arg
	f = os.path.splitext(f)[0]
	make_fonts(f)
	analyse(f)

if __name__ == '__main__':
	main(sys.argv[1:])
