#!/usr/bin/env python
# Only tested with Python2

from uni_create import create_for_files

import os, sys, getopt

def usage():
	print('create_font [-h] [-f <infont>] [-g <groups>] -o <outfont> [-c] <infiles>')
	print('<infont>: .ttf file')
	print('<groups>: .txt file')
	print('<outfont>: .otf file')
	print('<infiles>: .txt or .html files')
	sys.exit(2)

def main(argv):
	try:
		opts, args = getopt.getopt(argv, 'hf:g:o:c', [])
	except getopt.GetoptError:
		usage()
	d = os.path.dirname(os.path.realpath(sys.argv[0]))
	f = d + '/fonts/NewGardinerSMP'
	out = None
	custom_file = None
	complement = False
	for opt, arg in opts:
		if opt == '-h':
			usage()
		elif opt == '-f':
			f = d + '/fonts/' + arg
		elif opt == '-g':
			custom_file = arg
		elif opt == '-o':
			out = arg
		elif opt == '-c':
			complement = True
	if not out:
		usage()
	f = os.path.splitext(f)[0] 
	out = os.path.splitext(out)[0] 
	create_for_files(out, f, args, custom_file, complement)
	os.system('makeotf -f ' + out + '.ttf -ff ' + out + '.fea -o ' + out + '.otf')

if __name__ == '__main__':
	main(sys.argv[1:])
